import type { TokenLaunch } from '@/types'

export const MOCK_LAUNCHES: TokenLaunch[] = [
  {
    id: 'solpulse',
    name: 'SolPulse',
    symbol: 'PULSE',
    description: 'Real-time Solana network health monitoring with on-chain analytics. SolPulse provides dashboards, alerts, and API access for validators, protocols, and traders to monitor network performance.',
    logo: '💓',
    website: 'https://solpulse.io',
    twitter: '@solpulse_io',
    totalSupply: 100_000_000,
    launchPrice: 0.001,
    hardCap: 500,
    softCap: 100,
    raised: 312.5,
    minTier: 'silver',
    minScore: 35,
    maxAllocation: 10,
    tierBonuses: { platinum: 25, gold: 15, silver: 5, bronze: 0, public: 0 },
    startTime: '2026-02-15T00:00:00Z',
    endTime: '2026-02-22T00:00:00Z',
    status: 'live',
    participants: 47,
    vestingSchedule: '25% at TGE, 25% monthly over 3 months',
    tags: ['Infrastructure', 'Analytics', 'DePIN'],
  },
  {
    id: 'fairgov',
    name: 'FairGov',
    symbol: 'FGOV',
    description: 'Reputation-weighted DAO governance. Proposals and votes are weighted by FairScore, preventing plutocratic control and sybil attacks on DAOs.',
    logo: '🏛️',
    website: 'https://fairgov.xyz',
    twitter: '@fairgov_xyz',
    totalSupply: 50_000_000,
    launchPrice: 0.002,
    hardCap: 1000,
    softCap: 200,
    raised: 0,
    minTier: 'gold',
    minScore: 55,
    maxAllocation: 25,
    tierBonuses: { platinum: 30, gold: 20, silver: 10, bronze: 0, public: 0 },
    startTime: '2026-02-20T12:00:00Z',
    endTime: '2026-03-01T12:00:00Z',
    status: 'upcoming',
    participants: 0,
    vestingSchedule: '20% at TGE, linear vesting over 6 months',
    tags: ['Governance', 'DAO', 'Reputation'],
  },
  {
    id: 'depin-mesh',
    name: 'DePIN Mesh',
    symbol: 'MESH',
    description: 'Decentralized physical infrastructure network for IoT connectivity. Mesh node operators earn MESH tokens for providing coverage to smart devices.',
    logo: '📡',
    website: 'https://depinmesh.network',
    totalSupply: 1_000_000_000,
    launchPrice: 0.0005,
    hardCap: 2000,
    softCap: 500,
    raised: 1847.3,
    minTier: 'bronze',
    minScore: 15,
    maxAllocation: 50,
    tierBonuses: { platinum: 20, gold: 10, silver: 5, bronze: 2, public: 0 },
    startTime: '2026-02-10T00:00:00Z',
    endTime: '2026-02-14T00:00:00Z',
    status: 'ended',
    participants: 156,
    vestingSchedule: '15% at TGE, linear over 12 months',
    tags: ['DePIN', 'IoT', 'Infrastructure'],
  },
  {
    id: 'nft-fi',
    name: 'NFT-Fi Protocol',
    symbol: 'NFFI',
    description: 'Lending and borrowing against NFT collateral. Use your NFTs as collateral for instant SOL loans with reputation-based interest rates.',
    logo: '🎨',
    totalSupply: 200_000_000,
    launchPrice: 0.0015,
    hardCap: 750,
    softCap: 150,
    raised: 0,
    minTier: 'platinum',
    minScore: 75,
    maxAllocation: 15,
    tierBonuses: { platinum: 35, gold: 0, silver: 0, bronze: 0, public: 0 },
    startTime: '2026-03-01T00:00:00Z',
    endTime: '2026-03-08T00:00:00Z',
    status: 'upcoming',
    participants: 0,
    vestingSchedule: '10% at TGE, linear over 9 months',
    tags: ['NFT', 'DeFi', 'Lending'],
  },
  {
    id: 'solstream',
    name: 'SolStream',
    symbol: 'STRM',
    description: 'Decentralized streaming protocol on Solana. Stream payments per second for content creators, freelancers, and service providers.',
    logo: '🎬',
    website: 'https://solstream.xyz',
    totalSupply: 500_000_000,
    launchPrice: 0.0008,
    hardCap: 400,
    softCap: 80,
    raised: 400,
    minTier: 'silver',
    minScore: 30,
    maxAllocation: 20,
    tierBonuses: { platinum: 20, gold: 15, silver: 8, bronze: 3, public: 0 },
    startTime: '2026-02-01T00:00:00Z',
    endTime: '2026-02-08T00:00:00Z',
    status: 'distributed',
    participants: 89,
    vestingSchedule: '30% at TGE, 70% linear over 4 months',
    tags: ['Payments', 'Streaming', 'Creator Economy'],
  },
]

export function getLaunch(id: string): TokenLaunch | undefined {
  return MOCK_LAUNCHES.find(l => l.id === id)
}

export function getLiveLaunches(): TokenLaunch[] {
  return MOCK_LAUNCHES.filter(l => l.status === 'live')
}

export function getUpcomingLaunches(): TokenLaunch[] {
  return MOCK_LAUNCHES.filter(l => l.status === 'upcoming')
}

export function getEndedLaunches(): TokenLaunch[] {
  return MOCK_LAUNCHES.filter(l => l.status === 'ended' || l.status === 'distributed')
}
